- oc_modules/README.md
- oc_modules/oc_acl.rb
- oc_modules/oc_dublincore.rb
- oc_modules/oc_util.rb
- post-archive/README.md
- post-archive/post_archive.rb
- post-publish/README.md
- post-publish/post_publish.rb
Users of the post_publish script will now be able to pass metadata to Opencast in the same way as the post_archive script. This implicitly fixes the repository documentation, which never specified that passing metadata only worked for the post_archive integration.
To that end, the metadata-related code was outsourced into three modules in the new folder `oc_modules`. Both post processing scripts now require the presence of this folder to function.
The post_publish script was expanded to use the new modules. Furthermore, the single web-request to `/ingest/addMediapackage{wID}` was replaced by multiple web-requests (using the 'rest-client' gem), as the aforementioned endpoint does not offer a form field for ACLs.
Resolves #1.
> Added metadata support to the post_publish.rb script

- post-archive/README.md
- post-archive/bbb-upload.xml
- post-archive/post_archive.rb
This PR parses public chat messages from the events.xml into a subtitles file which can be send to Opencast and be displayed by the Paella Player.
As the Paella Player currently lacks functionality for displaying chat messages (as for example in twitch livestream recordings), displaying the chat as subtitles is the next best thing.
Drawbacks:
- Users cannot easily read past messages
- Rapid-fire messages are difficult to display in a readable way
Missing features:
- Line breaks for long messages
> Chat can now be send to Opencast as a subtitle file

- post-archive/post_archive.rb
In case files have already been processed to fix odd resolutions, the
integration will skip the work but then accidentally ingest the raw
recoding, not the prepared one.
This patch fixes that problem.
> Fix Upload of Prepared Files

- post-archive/post_archive.rb
The slide conversion to PNG seems to not work correctly with ImageMagick on Ubuntu >= 18.04 so I changed the converter to `rsvg-convert` and calling the command line tool directly in the `post-archive.rb` script (this needs the package `librsvg2-bin` installed to work) instead of using the `mini-magick` ruby gem.
> Use rsvg-convert instead of ImageMagick's convert.

- post-archive/README.md
The default partial-error workflow does not include material tagged
smil/source+partial and other source material and it's lost in case of errors.
https://github.com/opencast/opencast/blob/develop/etc/workflows/partial-error.xml#L34
> Suggest archive source material in partial error workflow

- post-archive/post_archive.rb
The config option already claimed that shared notes are send as attachments, but in the code they are send as catalogs. This fixes that.
Resolves #28
> Actually send shared notes as an attachment

- oc_modules/oc_dublincore.rb
It seems Opencast 9 requires a xml attribute that specifies the type of range for a "dublincore temporal" field. This adds that.
> Fixed metadata field "temporal" for Opencast 9

- README.md
- post-archive/post_archive.rb
- post-publish/post_publish.rb
Adds a new parameter 'opencast-add-webcams' that can be passed to the script just like metadata. It enables/disables sending webcams to Opencast (depending on the integration). If the parameter is not specified, intergrations will behave as they did previously.
> Added a new metadata parameter for webcams

- post-archive/post_archive.rb
The equals check does not work properly, as `meeting_metadata["opencast-add-webcams"]` is a Nokogiri Node, not it's value.
> Fix equals for add-webcams parameter

- post-archive/README.md
- post-archive/post_archive.rb
- post-publish/README.md
- post-publish/post_publish.rb
Solves the deprecation warning from https://github.com/elan-ev/opencast-bigbluebutton-integration/issues/43 commit.
And added the optimist gem to the readme
> Solves the deprecation warning

- post-archive/post_archive.rb
Enabling `deleteByBBBCron` did not work. The script threw an error:
```
/usr/local/bigbluebutton/core/scripts/post_archive/post_archive.rb:511:in `initialize': no implicit conversion of Array into String (TypeError)
```
This change fixes the problem.
> Fix deleteByBBBCron

- post-archive/post_archive.rb
- post-archive/post_archive_config.toml
HTML is useful for quickly viewing the shared notes (while the etherpad format is useful for seeing how the shared notes have created and to continue work).
> Send shared notes also as HTML

- post-archive/post_archive.rb
- post-archive/post_archive_config.toml
Hi @Arnei 
for better load balancing we use just one BBB instance (with scalelite) with Stud.IP, ILIAS and Greenlight as a frontend.
We'd like to process recordings from Stud.IP with Opencast and others with BBB. In order for this to work, we need to skip processing with the BBB integration if no series ID is set.
> Allow skip processing if no series ID is set

- post-archive/post_archive.rb
- post-archive/post_archive_config.toml
This commit introduces a new config parameter 'minimalDuration'.
This allows to define a minimal duration that recordings need to have
in order to be processed and send to Opencast.
The default is set to `0` which means that all recordings are normally processed.
Closes #49
> Allow to specify minimal recording duration

- post-publish/post_publish.rb
- post-publish/post_publish_config.toml
This commit applies the same type of logic that was introduced to
the post_arachive workflow in [#33](https://github.com/elan-ev/opencast-bigbluebutton-integration/pull/33)  to the post_publish workflow as well.
> add a config file to post_publish workflow

- post-publish/README.md
- post-publish/post_publish.rb
- post-publish/post_publish_config.toml
Adds support for the new bbb recording format "video". This format creates a single video file `video-0.m4v` from the webcam videos and the presentation video. If the old format `presentation` and the new format are enabled as described below, the `post_publish` script will be executed for each format, in this case twice. Then both formats will be ingested into opencast.
1. Add packages
```bash
apt-get install bbb-playback-video
```
2. Edit `/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml`
```yaml=
steps:
archive: "sanity"
sanity: "captions"
captions:
- "process:presentation"
- "process:video"
"process:presentation": "publish:presentation"
"process:video": "publish:video"
```
3. Restart processes
```bash
systemctl restart bbb-rap-resque-worker.service nginx
```
The latest …
> Add support for new recording format "video"

- oc_modules/oc_util.rb
Due to a misconfiguration, the script was failing to open a TCP connection to Opencast which caused an exception and caused the script to fail.
Unfortunately, this error was silenced and not logged at all, making it extremely hard to find out what was going on.
This patch makes sure that all errors are logged.
> Log All Ingest Errors

- oc_modules/oc_acl.rb
Opencast updated their series endpoint paths (in 12 and 13, yikes), which silently broke creating or updating series. This should fix that by updating the paths.
> Update Series endpoints

- oc_modules/oc_acl.rb
We were fetching all series just to check if one with our series id exists. This is not terribly performant, so we should simplify it.
> Simplify series exists check

- oc_modules/oc_util.rb
- post-publish/post_publish.rb
The post_publish script has not been sending the start and end times of the recording to Opencast. It relied on that information being in the metadata tag in the events.xml, where it simply was not. This would result in Opencast displaying the ingest time as the start time instead of the start time of the recording.
This patch fixes that by employing the same mechanism the post_archive script already uses, which is looking at the timestamps of the first and last events in the events.xml, and then using those values.
> Send real start and end times in post publish

- post-archive/post_archive.rb
Livekit produces a separate audio stream for webcams in BBB 3. This audio stream is handled with a new event in the `events.xml`. This commit makes sure that the livekit audio stream is also added to the tracks and sent to opencast.
FYI: The opencast workflows are already capable of combining the additional audio stream.
> Livekit Audio Fix
